sudo: required
language: java
jdk: openjdk8

env:
  global:
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - chmod +x mvnw
script: 
  - ./mvnw clean install -B
deploy:
 provider: heroku
 api_key: $HEROKU_API_KEY
 app: biblio-covid-utpl
